import React,{useState,useEffect,createContext,useContext} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,useNavigate,useLocation,Routes,Route,Link} from 'react-router-dom';
import {Search,MapPin,Heart,ShoppingBag,Menu,X,ChevronDown,Star,MessageCircle,Phone,Truck,ShieldCheck,Clock,Plus,Minus,Trash2,Check} from 'lucide-react';
import './styles.css';

const imgs=['https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800','https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800','https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800','https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=800','https://images.unsplash.com/photo-1507504031003-b417219a0fde?w=800','https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=800'];
const products=Array.from({length:18},(_,i)=>({id:i+1,title:['Elegant Birthday Balloon Arch','Midnight Anniversary Canopy','Little Star Baby Welcome','Pastel Rainbow Kids Theme','Rose Gold Romantic Surprise','Classic Balloon Bouquet'][i%6],price:[2499,3999,1899,2999,3499,999][i%6],mrp:[2799,4499,2299,3499,3999,1299][i%6],rating:(4.7+i%3/10).toFixed(1),reviews:120+i*17,img:imgs[i%imgs.length],tag:i%3===0?'BESTSELLER':i%3===1?'SAME DAY':''}));
const cats=[
  {name:'Birthday Decor',eyebrow:'Make it unforgettable',image:'https://cdn.7eventzz.com/images/48/62533447-a798-4931-977e-a8c790f8f1e0.webp',path:'/birthday-decorations'},
  {name:'Kids Birthday',eyebrow:'Big smiles for little ones',image:'https://cdn.7eventzz.com/images/48/84886dba-6b94-47be-9f82-391d5b8e3a2f.webp',path:'/kids-theme-decorations'},
  {name:'Newborn Welcome',eyebrow:'A warm welcome home',image:'https://cdn.7eventzz.com/images/48/2c1187e3-a232-4e3d-a299-20174e07cd55.webp',path:'/baby-welcome-decorations'},
  {name:'Baby Shower',eyebrow:'Little moments, big joy',image:'https://cdn.7eventzz.com/images/48/5d189911-9576-4d3a-9a97-fbc8f6cd6b51.webp',path:'/baby-shower-decorations'},
  {name:'Romantic',eyebrow:'Celebrate your story',image:'https://cdn.7eventzz.com/images/48/d6d2fa32-fda2-42e3-99fc-68713bbf9141.webp',path:'/room-decorations'},
  {name:'Wedding Decor',eyebrow:'Your day, beautifully styled',image:'https://cdn.7eventzz.com/images/48/7896fa4c-c0f9-40c3-8639-f04843b6f66e.webp',path:'/haldi-decorations'}
];
const homeProduct=(title,price,mrp,img,rating='4.9',reviews=72,path='/product/1')=>({id:title, title, price, mrp, img, rating, reviews, tag:'', path});
const homeCollections=[
  {title:'Birthday Balloon Decoration',sub:'Make their day extra special',path:'/birthday-decorations',items:[
    homeProduct('Simple Birthday Decoration at Home',2499,2799,'https://cdn.7eventzz.com/11/simple-birthday-decoration-at-home-1785562375292-177235.webp','4.9',472),
    homeProduct('Simple Birthday Decoration',1799,2099,'https://cdn.7eventzz.com/11/simple-birthday-decoration-1785222854831-958593.webp','4.8',112),
    homeProduct('Black and Silver Birthday Balloon Decoration at Home',6699,7599,'https://cdn.7eventzz.com/images/11/de3c853c-f969-4706-a549-69e17774e648.webp','4.8',459),
    homeProduct('Indoor Birthday Decoration',5999,6399,'https://cdn.7eventzz.com/images/11/6b732124-5506-4ca6-bb0c-40d7340ac0f4.webp','4.8',451),
    homeProduct('Simple Hall Decoration',1499,1999,'https://cdn.7eventzz.com/11/simple-hall-decoration-1785216516633-781870.webp','5.0',479)
  ]},
  {title:'Romantic Anniversary Decoration',sub:'Turn ordinary evenings into unforgettable memories',path:'/room-decorations',items:[
    homeProduct('Elegant 25th Anniversary Balloon Decoration',7699,8499,'https://cdn.7eventzz.com/images/12/091aa5fc-2742-42ad-8a10-a97154bd2a44.webp','4.9',122,'/decor/elegant-25th-anniversary-balloon-decoration'),
    homeProduct('Romantic Anniversary Backdrop with Red and Pink Balloon Arch',5499,6499,'https://cdn.7eventzz.com/images/12/8a44b75a-cdd5-42a4-96e2-dd66ff3ec39b.webp','4.9',128,'/decor/romantic-anniversary-backdrop-with-red-and-pink-balloon-arch'),
    homeProduct('Anniversary Balloon Room Decoration',2599,2999,'https://cdn.7eventzz.com/12/1741845620204.webp','4.6',15,'/decor/anniversary-balloon-room-decoration'),
    homeProduct('50th Premium Anniversary Decoration',7999,8999,'https://cdn.7eventzz.com/12/1741868570664.webp','4.7',18,'/decor/50th-premium-anniversary-decoration'),
    homeProduct('Lovely Anniversary Room Decoration',1799,2099,'https://cdn.7eventzz.com/12/1741843846145.webp','4.9',20,'/decor/lovely-anniversary-room-decoration'),
    homeProduct('Silver Jubilee Decoration',8499,9999,'https://cdn.7eventzz.com/12/1742016082150.webp','4.8',61,'/decor/silver-jubilee-decoration')
  ]},
  {title:'Newborn Welcome Decor',sub:'Welcome your little one in style',path:'/baby-welcome-decorations',items:[
    homeProduct('Welcome Baby Flower Decoration',3999,4999,'https://cdn.7eventzz.com/images/42/bcbd7db5-db12-4761-9eb3-f0e8b4dfaa46.webp','4.9',169,'/decor/welcome-baby-flower-decoration'),
    homeProduct('Welcome Baby Girl Decoration',3499,3999,'https://cdn.7eventzz.com/16/welcome-baby-girl-decoration-1785505129170-37810.webp','4.7',167,'/decor/welcome-baby-girl-decoration'),
    homeProduct('Pink Theme Baby Welcome Decor with Flowers',3799,4599,'https://cdn.7eventzz.com/images/42/80f32a47-5ea4-4ff2-b94b-bd521b728c1b.webp','5.0',293,'/decor/pink-theme-baby-welcome-decor-with-flowers'),
    homeProduct('Baby Boy Home Setup',3799,4499,'https://cdn.7eventzz.com/images/42/0b4041b1-3743-472c-a5f0-abb9414f38e6.webp','4.7',85,'/decor/baby-boy-home-setup'),
    homeProduct('Dazzling Baby Welcome',3799,4499,'https://cdn.7eventzz.com/images/42/da6ff8fa-7071-4dfb-b13c-1920aa90deb9.webp','4.7',29,'/decor/dazzling-baby-welcome'),
    homeProduct('Welcome New Born Baby Decoration',6499,6999,'https://cdn.7eventzz.com/images/42/b8eccd82-32e4-412c-b932-5e0974e7b0a9.webp','4.9',281,'/decor/welcome-new-born-baby-decoration')
  ]},
  {title:'Customized Balloon Bouquet',sub:'Send a gift of love',path:'/balloon-bouquets',items:[
    homeProduct('Chocolate Balloon Bouquet',2399,3099,'https://cdn.7eventzz.com/39/1784551386614-108522.webp','4.8',98,'/decor/chocolate-balloon-bouquet'),
    homeProduct('Customized Anniversary Hamper',2499,3999,'https://cdn.7eventzz.com/39/1784554992686-465353.webp','5.0',17,'/decor/customized-anniversary-hamper'),
    homeProduct('Rose Flower Bouquet',2299,3099,'https://cdn.7eventzz.com/39/1784555025644-954871.webp','4.9',69,'/decor/rose-flower-bouquet'),
    homeProduct('Anniversary Balloon Bouquet',1799,2399,'https://cdn.7eventzz.com/39/1784611574845-840012.webp','5.0',54,'/decor/anniversary-balloon-bouquet'),
    homeProduct('Car Theme Balloon Bouquet',1799,2199,'https://cdn.7eventzz.com/39/1784555346395-201078.webp','4.7',17,'/decor/car-theme-balloon-bouquet'),
    homeProduct('Cheers to Birthday Balloon setup',2299,2899,'https://cdn.7eventzz.com/39/1784553961393-441872.webp','4.7',317,'/decor/cheers-to-birthday-balloon-setup')
  ]},
  {title:'Baby Shower Packages',sub:'Celebrate the parents-to-be',path:'/baby-shower-decorations',items:[
    homeProduct('Gender Reveal Backdrop with Pink & Blue Balloon Arch',6499,7499,'https://cdn.7eventzz.com/images/15/670e3949-15ef-471a-ba9b-4be5580279ec.webp','4.9',461,'/decor/gender-reveal-backdrop-with-pink--blue-balloon-arch'),
    homeProduct('Modern Oh Baby Party Backdrop with Blue Balloon Arch',5799,6299,'https://cdn.7eventzz.com/images/15/375448e3-6e63-4435-a0e3-f9138d4f97b5.webp','4.8',457,'/decor/modern-oh-baby-party-backdrop-with-blue-balloon-arch'),
    homeProduct('Krishna Theme Baby Shower Decoration with Balloon Arch',6499,7499,'https://cdn.7eventzz.com/images/15/5d6d6828-9cee-45f8-abd8-89691cbcb40d.webp','4.8',466,'/decor/krishna-theme-baby-shower-decoration-with-balloon-arch'),
    homeProduct('Simple Baby Shower Wall Decoration',2199,2599,'https://cdn.7eventzz.com/15/simple-baby-shower-wall-decoration-1785501543905-284754.webp','4.9',99,'/decor/simple-baby-shower-wall-decoration'),
    homeProduct('Elegant Oh Baby Balloon Decoration with Blue & Gold Arch Backdrop',7499,8499,'https://cdn.7eventzz.com/images/15/c3cd8c95-5bbb-4eb2-a3e5-72582a74b5e0.webp','4.9',453,'/decor/elegant-oh-baby-balloon-decoration-with-blue--gold-arch-backdrop'),
    homeProduct('Premium Baby Shower Balloon Decoration',6999,7599,'https://cdn.7eventzz.com/images/15/a77cd208-679e-4478-9d3e-6093ea115dd5.webp','4.9',97,'/decor/premium-baby-shower-balloon-decoration'),
    homeProduct('Oh Baby Setup Decoration',4499,4999,'https://cdn.7eventzz.com/images/15/80d0b5fd-6aef-4c2e-b903-cb485f038bc7.webp','4.9',54,'/decor/oh-baby-setup-decoration')
  ]},
  {title:'Car Boot Surprise Decorations',sub:'Unique Surprise',path:'/car-boot-decorations',items:[
    homeProduct('Anniversary Car Decor',2499,2999,'https://cdn.7eventzz.com/14/anniversary-car-decor-1785582782425-47039.webp','4.6',13,'/decor/anniversary-car-decor'),
    homeProduct('Birthday Decoration In Car',2099,2299,'https://cdn.7eventzz.com/14/birthday-decoration-in-car-1785582190898-557335.webp','4.9',32,'/decor/birthday-decoration-in-car'),
    homeProduct('Premium Car Decor',2499,2999,'https://cdn.7eventzz.com/14/1742186324988.webp','4.9',28,'/decor/premium-car-decor'),
    homeProduct('Birthday Decoration for Car Boot',2299,2799,'https://cdn.7eventzz.com/14/1741872458811.webp','4.8',57,'/decor/birthday-decoration-for-car-boot'),
    homeProduct('Car Boot Surprise',1499,1799,'https://cdn.7eventzz.com/14/car-boot-surprise-1785581691040-868938.webp','4.6',99,'/decor/car-boot-surprise')
  ]}
];
const kidsSpecial=[
  ['Baby Ceremony','https://cdn.7eventzz.com/images/48/1789c020-1887-4c1f-8acd-8446b142e890.webp','/ceremony-decorations'],
  ['1st Birthday','https://cdn.7eventzz.com/images/48/b07e0d61-8bc8-4d58-b2ed-52345495870f.webp','/kids-theme-decorations'],
  ['Kids Activity','https://cdn.7eventzz.com/images/48/eae2d1c1-1ece-49eb-b07c-bfb6c99ab374.webp','/kids-activities'],
  ['Stage Decor','https://cdn.7eventzz.com/images/48/0dfa57d9-92a6-4438-8bcb-aea593cd4bcb.webp','/stage-decorations'],
  ['Annaprashan','https://cdn.7eventzz.com/images/48/c432e032-a4c9-448b-bc45-e15abba121dd.webp','/ceremony-decorations/annaprashan-rice'],
  ['Naming Ceremony','https://cdn.7eventzz.com/images/48/34026d38-bac3-4167-a621-ff461c72e6c5.webp','/ceremony-decorations/naming']
];
const romanticDecor=[
  ['Anniversary','https://cdn.7eventzz.com/images/48/9d3aa4c2-77ee-4f00-9fed-2383dacce431.webp','/anniversary-decorations'],
  ['Canopy Decor','https://cdn.7eventzz.com/images/48/d9330f52-0f78-426f-8c9b-c31bd8eee5ee.webp','/canopy-decorations'],
  ['Room Decor','https://cdn.7eventzz.com/images/48/2ccb238f-8e9d-4ae4-83ad-215ac1dbf7ed.webp','/room-decorations'],
  ['Proposal','https://cdn.7eventzz.com/images/48/3cef6a0c-d193-4648-8f66-7491de33a8d9.webp','/proposal-decorations'],
  ['Car Boot','https://cdn.7eventzz.com/images/48/07b21205-ae82-4513-a8c1-619b4ab566a6.webp','/car-boot-decorations'],
  ['Candle Light Dinner','https://cdn.7eventzz.com/images/48/a664b7f6-6cdd-49b1-8bc7-f451126df294.webp','/candle-light-dinner']
];
const cities=['Delhi','Mumbai','Bangalore','Hyderabad','Pune','Chennai','Kolkata','Ahmedabad','Jaipur','Gurgaon','Noida','Chandigarh','Agra','Indore','Lucknow','Surat','Vadodara','Udaipur','Jodhpur','Bhopal'];
const localAreas={Ahmedabad:['Satellite','Bodakdev','Prahlad Nagar','Vastrapur','Navrangpura','Maninagar','Gota','Chandkheda','Bopal','Thaltej'],Gandhinagar:['Kudasan','Sargasan','Infocity','Randesan','Adalaj','Sector 11','Sector 21','Gift City','Mansa Road','Chiloda']};
const navMenus=[
  {label:'Birthday',path:'/decorations/birthday',items:['Birthday Balloon Decoration','1st Birthday Decor','Kids Birthday Themes','Birthday Balloon Arch','Birthday Party Backdrops']},
  {label:'Balloon Decor',path:'/decorations/balloon',items:['Balloon Arches','Balloon Bouquets','Organic Balloon Decor','Number Balloons','Balloon Backdrops']},
  {label:'Anniversary',path:'/decorations/anniversary',items:['Romantic Room Decoration','Anniversary Balloon Decor','Candlelight Setup','Proposal Decoration','Surprise Decoration']},
  {label:'Baby & Kids',path:'/decorations/baby-shower',items:['Baby Shower Decor','Newborn Welcome','Naming Ceremony','Kids Theme Decor','First Birthday']},
  {label:'Wedding',path:'/decorations/wedding',items:['Engagement Decoration','Haldi Decoration','Mehendi Decoration','Wedding Backdrops','Reception Decor']},
  {label:'Cities',path:'/city/delhi',items:cities.slice(0,8),extra:'View all 20+ cities'},
  {label:'More',path:'/about',groups:[
    {title:'Venue & Setup',items:[['Room Decorations','/room-decorations'],['Stage Decorations','/stage-decorations'],['Canopy Decorations','/canopy-decorations'],['Terrace Decorations','/terrace-decorations'],['Premium Decorations','/premium-decorations'],['Car Boot Decorations','/car-boot-decorations']]},
    {title:'Occasions',items:[['Congratulation Decorations','/congratulation-decorations'],['Retirement Decorations','/retirement-decorations'],['Housewarming Decorations','/housewarming-decorations'],['Office Decorations','/office-decorations'],['Halloween Decorations','/halloween-decorations']]},
    {title:'Festivals & Faith',items:[['Ganpati Decorations','/ganpati-decorations'],['Ganpati Ahmedabad','/ganpati-decorations/ahmedabad'],['Ganpati Gandhinagar','/ganpati-decorations/gandhinagar'],['Guruji Decorations','/guruji-decorations']]},
    {title:'Add-ons',items:[['Balloon Bouquets','/balloon-bouquets'],['Flower Decorations','/flower-decorations'],['Kids Activities','/kids-activities']]}
  ],extra:'Contact our experts'}
];
const AppContext=createContext();
function WhatsAppIcon(){return <svg className="whatsappIcon" viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M20.52 3.48A11.8 11.8 0 0 0 12.12 0C5.58 0 .26 5.32.26 11.86c0 2.09.55 4.13 1.59 5.93L.16 24l6.35-1.66a11.86 11.86 0 0 0 5.61 1.42h.01c6.54 0 11.86-5.32 11.86-11.86 0-3.17-1.23-6.15-3.47-8.42Zm-8.4 18.25h-.01a9.84 9.84 0 0 1-5.02-1.37l-.36-.22-3.77.99 1.01-3.67-.24-.38a9.83 9.83 0 0 1-1.51-5.22C2.22 6.43 6.66 1.99 12.12 1.99c2.64 0 5.12 1.03 6.98 2.89a9.82 9.82 0 0 1 2.88 6.99c0 5.46-4.44 9.9-9.86 9.9Zm5.43-7.42c-.3-.15-1.76-.87-2.03-.97-.27-.1-.47-.15-.67.15-.2.3-.77.97-.94 1.17-.17.2-.35.22-.65.07-.3-.15-1.26-.46-2.4-1.48-.89-.79-1.49-1.77-1.66-2.07-.17-.3-.02-.46.13-.61.13-.13.3-.35.45-.52.15-.17.2-.3.3-.5.1-.2.05-.37-.02-.52-.07-.15-.67-1.61-.92-2.2-.24-.57-.49-.5-.67-.51h-.57c-.2 0-.52.07-.79.37-.27.3-1.04 1.02-1.04 2.49s1.07 2.89 1.22 3.09c.15.2 2.1 3.2 5.09 4.49.71.31 1.27.49 1.7.63.72.23 1.38.2 1.9.12.58-.09 1.76-.72 2.01-1.42.25-.7.25-1.3.17-1.42-.07-.12-.27-.2-.57-.35Z"/></svg>}
function Store({children}){const [cart,setCart]=useState(()=>JSON.parse(localStorage.getItem('eb-cart')||'[]'));const [wish,setWish]=useState(()=>JSON.parse(localStorage.getItem('eb-wish')||'[]'));const [city,setCity]=useState(()=>localStorage.getItem('eb-city')||'Delhi');useEffect(()=>localStorage.setItem('eb-cart',JSON.stringify(cart)),[cart]);useEffect(()=>localStorage.setItem('eb-wish',JSON.stringify(wish)),[wish]);useEffect(()=>localStorage.setItem('eb-city',city),[city]);const add=p=>setCart(c=>[...c,p]);const toggle=p=>setWish(w=>w.some(x=>x.id===p.id)?w.filter(x=>x.id!==p.id):[...w,p]);return <AppContext.Provider value={{cart,setCart,wish,toggle,add,city,setCity}}>{children}</AppContext.Provider>}
function Header(){const {city,setCity}=useContext(AppContext);const [drawer,setDrawer]=useState(false),[cityOpen,setCityOpen]=useState(false),[q,setQ]=useState('');const nav=useNavigate();return <><div className="trust"><span>⚡ Fast setup</span><span>✓ 10,000+ celebrations</span><span>🛡 Quality assured</span><span>📍 Serving 20+ cities</span></div><header><div className="head"><button className="hamb" onClick={()=>setDrawer(true)}><Menu/></button><Link to="/" className="logo"><span>THE</span><b>BALLOON ATELIER</b></Link><button className="location" onClick={()=>setCityOpen(true)}><MapPin size={17}/><span>{city}</span><ChevronDown size={14}/></button><div className="search"><Search size={19}/><input placeholder="Search decorations, themes..." value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&nav('/search?q='+q)}/>{q&&<div className="suggest"><b>Products</b>{products.filter(p=>p.title.toLowerCase().includes(q.toLowerCase())).slice(0,4).map(p=><div onClick={()=>nav('/product/'+p.id)} key={p.id}>{p.title}</div>)}<b>Popular searches</b><div>Birthday decoration</div><div>Balloon bouquet</div></div>}</div><nav className="topnav"><Link to="/decorations/birthday">Birthday</Link><Link to="/decorations/anniversary">Anniversary</Link><Link to="/decorations/baby-shower">Baby & Kids</Link><Link to="/decorations/wedding">Wedding</Link><Link to="/decorations/balloon">Balloon Decor</Link></nav><div className="actions"><a className="headerContact call" href="tel:+919999999999"><Phone size={17}/> <span>Call us</span></a><a className="headerContact whatsapp" href="https://wa.me/919999999999"><WhatsAppIcon/><span>WhatsApp</span></a></div><nav className="mainnav">{navMenus.map(menu=><div className="navitem" key={menu.label}><Link to={menu.path}>{menu.label}<ChevronDown size={13}/></Link><div className={'navdropdown '+(menu.groups?'megaDropdown':'')}><strong>{menu.label} decoration</strong>{menu.groups?<div className="navgroups">{menu.groups.map(group=><div className="navgroup" key={group.title}><h4>{group.title}</h4>{group.items.map(([item,path])=><Link to={path} key={item}>{item}</Link>)}</div>)}</div>:<div className="navoptions">{menu.items.map(item=><Link to={menu.path} key={item}>{item}</Link>)}</div>}{menu.extra&&<Link className="navmore" to={menu.path}>{menu.extra} →</Link>}</div></div>)}</nav></div><div className="mobile-search search"><Search size={18}/><input placeholder="Search decorations..." onKeyDown={e=>e.key==='Enter'&&nav('/search?q='+e.target.value)}/></div></header>{drawer&&<div className="overlay" onClick={()=>setDrawer(false)}><aside onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setDrawer(false)}><X/></button><div className="logo"><span>THE</span> <b>BALLOON ATELIER</b></div>{navMenus.map(menu=><Link key={menu.label} to={menu.path} onClick={()=>setDrawer(false)}>{menu.label}<ChevronDown size={16}/></Link>)}</aside></div>}{cityOpen&&<CityModal close={()=>setCityOpen(false)} setCity={setCity}/>}</>}
function CityModal({close,setCity}){const [q,setQ]=useState('');let list=cities.filter(c=>c.toLowerCase().includes(q.toLowerCase()));return <div className="modalbg" onClick={close}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button><h2>Select your city</h2><p>See decorations available near you</p><input className="cityinput" placeholder="Search city..." value={q} onChange={e=>setQ(e.target.value)}/><h4>Popular cities</h4><div className="citygrid">{list.map(c=><button key={c} onClick={()=>{setCity(c);close()}}>{c}</button>)}</div></div></div>}
function ProductCard({p}){const {wish,toggle,add}=useContext(AppContext);const productPath=p.path||'/product/'+p.id;return <article className="card"><Link to={productPath}><div className="pic"><img src={p.img} loading="lazy"/>{p.tag&&<label>{p.tag}</label>}</div></Link><button className={'heart '+(wish.some(x=>x.id===p.id)?'on':'')} onClick={()=>toggle(p)}><Heart size={18} fill="currentColor"/></button><Link to={productPath}><h3>{p.title}</h3></Link><div className="rating"><Star size={14} fill="currentColor"/> {p.rating} <span>({p.reviews})</span></div><b className="price">₹{p.price.toLocaleString()}</b> <del>₹{p.mrp.toLocaleString()}</del><em>{Math.round((1-p.price/p.mrp)*100)}% OFF</em><button className="quick" onClick={()=>add(p)}>Add to cart</button></article>}
function Hero(){return <section className="hero"><div><label className="heroBadge">✨ FESTIVE FAVOURITES</label><p>MAKE EVERY MOMENT</p><h1>Beautiful celebrations,<br/><i>effortlessly arranged.</i></h1><span>Thoughtful decor, delivered and styled at your doorstep.</span><Link className="btn" to="/decorations/birthday">Explore decorations →</Link></div></section>}
function ProductSection({title,sub,items=products.slice(0,6),path='/decorations/birthday'}){return <section className="section"><div className="sectionhead"><div><h2>{title}</h2><p>{sub}</p></div><Link to={path}>View all →</Link></div><div className="grid">{items.map((p,i)=><ProductCard key={p.id||i} p={p}/>)}</div></section>}
function PageSEO({title='The Balloon Atelier | Event Decorations & Balloon Decor'}){useEffect(()=>{document.title=title;const meta=document.querySelector('meta[name="description"]');if(meta) meta.setAttribute('content','Beautiful event decorations and balloon setups delivered by verified decorators across India.');},[title]);return null}
function CollectionTiles({title,sub,items}){return <section className="section tileSection"><div className="sectionhead"><div><h2>{title}</h2><p>{sub}</p></div></div><div className="tileRow">{items.map(([name,image,path])=><Link className="tileCard" to={path} key={name}><img src={image}/><b>{name}</b></Link>)}</div></section>}
function Home(){return <><Hero/><section className="section categories"><div className="sectionhead"><div><span className="sectionKicker">SHOP BY OCCASION</span><h2>Top Balloon Decoration Categories</h2><p>Trusted decorators for all events</p></div><Link to="/birthday-decorations">Browse all <span aria-hidden="true">→</span></Link></div><div className="catrow">{cats.map(c=><Link className="catCard" to={c.path} key={c.name}><div className="catImage"><img src={c.image}/><span>Explore <span aria-hidden="true">↗</span></span></div><div className="catCopy"><b>{c.name}</b><small>{c.eyebrow}</small></div></Link>)}</div></section><ProductSection {...homeCollections[0]}/><CollectionTiles title="Kids Special" sub="Beautiful setups for their happiest milestones" items={kidsSpecial}/><CollectionTiles title="Romantic Decor" sub="Decoration For Couple Celebration" items={romanticDecor}/>{homeCollections.slice(1).map(collection=><ProductSection key={collection.title} {...collection}/>)}<Inquiry/><SEO/><Reviews/></>}
function Inquiry(){const [sent,setSent]=useState(false);return <section className="inquiry"><div><h2>Planning something special?</h2><p>Tell us what you have in mind and our celebration experts will call you back.</p></div>{sent?<div className="success"><Check/> Thanks! We'll call you shortly.</div>:<form onSubmit={e=>{e.preventDefault();setSent(true)}}><input required placeholder="Your name"/><input required placeholder="Phone number"/><button className="btn">Send inquiry</button></form>}</section>}
function SEO(){return <section className="seo"><h2>Balloon Decoration at Home in Ahmedabad & Gandhinagar</h2><p>The Balloon Atelier brings premium birthday, anniversary, baby shower, romantic room, balloon bouquet and surprise decorations to your doorstep. Packages start at ₹999 and our decorators bring all materials, complete the setup on time and leave your space celebration-ready.</p><div className="localGrid">{Object.entries(localAreas).map(([city,areas])=><div className="localCard" key={city}><h3>Decoration near me in {city}</h3><p>{areas.map((area,i)=><Link to={'/city/'+city.toLowerCase()} key={area}>{area}{i<areas.length-1?' · ':''}</Link>)}</p></div>)}</div><div className="table"><div><b>Package type</b><b>Price range</b><b>What's included</b></div>{[['Basic balloon decoration','₹999 – ₹1,499','Balloons, ribbons & setup'],['Birthday decoration','₹1,499 – ₹2,499','Foil balloons, backdrop & name'],['Premium decoration','₹10,999+','Custom backdrop, lights & props']].map(r=><div key={r[0]}>{r.map(x=><span key={x}>{x}</span>)}</div>)}</div><h3>How booking works</h3><p>Choose a design, select Ahmedabad or Gandhinagar, share your event date and confirm online. For same-day bookings, call or WhatsApp our team directly.</p><h3>Frequently Asked Questions</h3><div className="faq"><details><summary>What decorations can I book?</summary><p>Birthday, anniversary, baby shower, newborn welcome, proposal, balloon bouquet, stage, canopy and car boot decorations.</p></details><details><summary>Do you serve local areas?</summary><p>Yes, we currently focus on Ahmedabad and Gandhinagar, including the areas listed above.</p></details><details><summary>What does the price include?</summary><p>The decorator brings the balloons and setup material. The final package inclusions are shown before booking.</p></details></div><div className="seoCta"><b>100% Purely Bhartiya Brand 🇮🇳</b><span>Live in Ahmedabad & Gandhinagar · Same-day booking available</span></div></section>}
function Reviews(){return <section className="section reviews"><div className="sectionhead"><div><h2>Loved by thousands of hosts</h2><p>Real celebrations, real smiles</p></div></div><div className="reviewrow">{['“The decorator was punctual and the setup looked even better than the photos. Truly effortless!”','“Our daughter was thrilled with her rainbow theme. Great communication from start to finish.”','“Booked at short notice and they made it happen beautifully. Highly recommend The Balloon Atelier.”'].map((x,i)=><div className="review" key={x}><div className="rating">★★★★★</div><p>{x}</p><b>{['Ananya · Mumbai','Rohit · Delhi','Meera · Bangalore'][i]}</b><small>✓ Verified booking</small></div>)}</div></section>}
function Listing(){const loc=useLocation();const term=new URLSearchParams(loc.search).get('q');const title=term?'Search results for "'+term+'"':(loc.pathname.split('/').pop().replaceAll('-',' ')||'decorations');const [sort,setSort]=useState('Recommended');let shown=term?products.filter(p=>p.title.toLowerCase().includes(term.toLowerCase())):products;shown=[...shown].sort((a,b)=>sort==='Price Low to High'?a.price-b.price:sort==='Price High to Low'?b.price-a.price:sort==='Highest Rated'?b.rating-a.rating:0);return <main className="listing"><PageSEO title={`${title} | The Balloon Atelier`}/><div className="crumb">Home / Decorations / {title}</div><h1>{title.replace(/\b\w/g,c=>c.toUpperCase())}</h1><p>Discover thoughtfully designed setups, delivered and styled by verified decorators.</p><div className="listingbar"><b>{shown.length} designs</b><select value={sort} onChange={e=>setSort(e.target.value)}><option>Recommended</option><option>Price Low to High</option><option>Price High to Low</option><option>Highest Rated</option></select></div><div className="listingbody"><aside className="filters"><h3>Filter by</h3>{['Price','Rating','Occasion','Theme','Color','Location','Availability'].map(x=><label key={x}>{x}<ChevronDown size={15}/></label>)}</aside><div className="grid">{shown.map(p=><ProductCard p={p} key={p.id}/>)}</div></div></main>}
function Product(){const {add}=useContext(AppContext);const id=Number(useLocation().pathname.split('/').pop());const p=products.find(x=>x.id===id)||products[0];const [date,setDate]=useState('');return <main className="detail"><div className="gallery"><img src={p.img}/><div>{imgs.slice(0,4).map(x=><img src={x} key={x}/>)}</div></div><div className="buy"><div className="crumb">Home / {p.title}</div><h1>{p.title}</h1><div className="rating"><Star size={16} fill="currentColor"/> {p.rating} <span>({p.reviews} reviews)</span></div><h2>₹{p.price.toLocaleString()} <del>₹{p.mrp}</del> <em>Save {Math.round((1-p.price/p.mrp)*100)}%</em></h2><hr/><label>Event date</label><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><label>Choose a package</label><select><option>Standard setup · Included</option><option>Premium setup + ₹1,500</option></select><div className="trustnotes"><span><ShieldCheck/> Verified decorator</span><span><Clock/> On-time setup</span><span><Truck/> Secure payment</span></div><button className="btn wide" onClick={()=>add({...p,date})}>Add to cart</button><button className="wa"><MessageCircle/> Need help? Chat on WhatsApp</button></div><div className="info"><h2>About this decoration</h2><p>A picture-perfect celebration setup designed with premium balloons, thoughtful details and a clean finish. Our decorators bring, set up and clear everything after your event.</p><h3>What's included</h3><p>Backdrop styling, balloons, name foil and professional setup. Custom colors and messages available on request.</p></div></main>}
function Cart(){const {cart,setCart}=useContext(AppContext);let total=cart.reduce((s,p)=>s+p.price,0);return <main className="cartpage"><h1>Your cart</h1>{!cart.length?<div className="empty"><ShoppingBag size={44}/><h2>Your cart is waiting</h2><Link className="btn" to="/">Browse decorations</Link></div>:<div className="cartlayout"><div>{cart.map((p,i)=><div className="cartitem" key={i}><img src={p.img}/><div><h3>{p.title}</h3><p>{p.date||'Date to be confirmed'} · {p.city||'Delhi'}</p><b>₹{p.price.toLocaleString()}</b></div><button onClick={()=>setCart(c=>c.filter((_,j)=>j!==i))}><Trash2 size={18}/></button></div>)}</div><div className="summary"><h2>Order summary</h2><p>Subtotal <b>₹{total.toLocaleString()}</b></p><p>Convenience fee <b>₹99</b></p><hr/><h3>Total <b>₹{(total+99).toLocaleString()}</b></h3><Link className="btn wide" to="/checkout">Proceed to checkout</Link></div></div>}</main>}
function Checkout(){return <main className="checkout"><div><h1>Checkout</h1><div className="steps">1 Customer details　 2 Event details　 3 Address　 4 Payment</div><form onSubmit={e=>{e.preventDefault();alert('Booking request received!')}}><h2>Customer details</h2><input required placeholder="Full name"/><input required placeholder="Phone number"/><input type="email" required placeholder="Email address"/><h2>Event address</h2><input required placeholder="House / Flat"/><input required placeholder="Street and area"/><input required placeholder="City"/><input required placeholder="PIN code"/><h2>Event details</h2><input type="date" required/><textarea placeholder="Special instructions"></textarea><button className="btn wide">Place booking request</button></form></div><div className="summary"><h2>Secure checkout</h2><p>✓ Verified decorators</p><p>✓ Secure payments</p><p>✓ Easy rescheduling</p></div></main>}
function Login(){const [sent,setSent]=useState(false);return <main className="login"><div className="loginbox"><div className="logo"><span>THE</span> <b>BALLOON ATELIER</b></div><h1>{sent?'Enter your OTP':'Welcome back'}</h1><p>{sent?'We sent a 6-digit code to your phone.':'Login to manage bookings and wishlists.'}</p>{sent?<><div className="otp">{[1,2,3,4,5,6].map(i=><input key={i} maxLength="1"/>)}</div><button className="btn wide">Verify & continue</button></>:<><input placeholder="Enter mobile number"/><button className="btn wide" onClick={()=>setSent(true)}>Send OTP</button></>}</div></main>}
function InfoPage({title,children}){return <main className="listing infoPage"><PageSEO title={`${title} | The Balloon Atelier`}/><h1>{title}</h1><p>{children||'The Balloon Atelier makes every celebration easier with verified decorators, transparent pricing and thoughtful service.'}</p></main>}
function Footer(){const links=[['Popular services',['/decorations/birthday','/decorations/balloon','/decorations/anniversary','/decorations/baby-shower'],['Birthday decoration','Balloon bouquets','Anniversary decor','Baby welcome']],['Local areas',['/city/ahmedabad','/city/ahmedabad','/city/gandhinagar','/city/gandhinagar'],['Ahmedabad','Satellite · Bodakdev','Gandhinagar','Kudasan · Sargasan']],['Company',['/about','/contact','/privacy-policy','/terms'],['About us','Contact us','Privacy policy','Terms & conditions']]];return <footer><div className="foottrust"><span>🇮🇳 Made in India</span><span>🎉 10,000+ celebrations</span><span>✓ Verified decorators</span><span>🔒 Secure payments</span></div><div className="footerMain"><div className="footerIntro"><div className="logo"><span>THE</span> <b>BALLOON ATELIER</b></div><h3>Make every moment<br/><i>beautifully unforgettable.</i></h3><p>Premium balloon decor, thoughtful details and reliable setup for celebrations across Ahmedabad and Gandhinagar.</p><div className="footerContact"><a href="tel:+919999999999"><Phone size={16}/> +91 99999 99999</a><a href="https://wa.me/919999999999"><WhatsAppIcon/> Chat on WhatsApp</a></div></div><div className="footLinks">{links.map(([h,hrefs,xs])=><div key={h}><h4>{h}</h4>{xs.map((x,i)=><Link to={hrefs[i]} key={x}>{x}</Link>)}</div>)}</div></div><div className="footerBottom"><span>© 2026 The Balloon Atelier. Made for memorable moments.</span><span>Serving Ahmedabad · Gandhinagar</span></div></footer>}
function BottomNav(){return <div className="bottomnav"><Link to="/"><span>⌂</span>Home</Link><Link to="/decorations/birthday"><span>✦</span>Explore</Link><a href="https://wa.me/919999999999"><MessageCircle/>Chat</a><a href="tel:+919999999999"><Phone/>Call</a><Link to="/account"><span>♙</span>Account</Link></div>}
function App(){return <Store><PageSEO/><Header/><Routes><Route path="/" element={<Home/>}/><Route path="/decorations/*" element={<Listing/>}/><Route path="/category/:slug" element={<Listing/>}/><Route path="/decor/:slug" element={<Listing/>}/><Route path="/city/:citySlug" element={<Listing/>}/><Route path="/search" element={<Listing/>}/><Route path="/product/:id" element={<Product/>}/><Route path="/cart" element={<Cart/>}/><Route path="/wishlist" element={<Wishlist/>}/><Route path="/checkout" element={<Checkout/>}/><Route path="/login" element={<Login/>}/><Route path="/account" element={<InfoPage title="Your account"/>}/><Route path="/account/orders" element={<InfoPage title="Your orders"/>}/><Route path="/contact" element={<InfoPage title="Contact The Balloon Atelier"/>}/><Route path="/about" element={<InfoPage title="About The Balloon Atelier"/>}/><Route path="/privacy-policy" element={<InfoPage title="Privacy policy"/>}/><Route path="/terms" element={<InfoPage title="Terms & conditions"/>}/><Route path="/cancellation-policy" element={<InfoPage title="Cancellation policy"/>}/></Routes><Footer/><a className="floatwa"><MessageCircle/></a><BottomNav/></Store>}
function Wishlist(){const {wish}=useContext(AppContext);return <main className="listing"><h1>Your wishlist</h1>{wish.length?<div className="grid">{wish.map(p=><ProductCard p={p} key={p.id}/>)}</div>:<div className="empty"><Heart size={44}/><h2>Save your favourites here</h2><Link className="btn" to="/">Explore decorations</Link></div>}</main>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
